/**
 * Waits for the Hermes session id of a freshly-spawned `hermes chat` to appear
 * in `state.db`. A fresh local session's id is generated by Hermes on launch
 * (Happier cannot pre-assign it — `--resume <fresh-id>` errors), so the mirror
 * polls `sessions` for the newest row started at/after the launch instant.
 * Returns null if none appears before the timeout.
 */
import type { SqliteDatabaseSync } from '@/daemon/memory/sqliteSync';

import { discoverHermesSessionIdSince } from './hermesSessionDiscovery';
import { openHermesSessionStore } from './hermesSessionStore';

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function tryDiscover(
  openStore: (path: string) => SqliteDatabaseSync,
  stateDbPath: string,
  sinceEpochSeconds: number,
): string | null {
  let db: SqliteDatabaseSync | null = null;
  try {
    db = openStore(stateDbPath);
    return discoverHermesSessionIdSince(db, sinceEpochSeconds);
  } catch {
    // state.db may not exist yet immediately after launch; keep waiting.
    return null;
  } finally {
    try {
      db?.close();
    } catch {
      // ignore close failures on a read-only handle
    }
  }
}

export async function waitForHermesSessionId(params: Readonly<{
  stateDbPath: string;
  sinceEpochSeconds: number;
  timeoutMs: number;
  intervalMs: number;
  openStore?: (path: string) => SqliteDatabaseSync;
}>): Promise<string | null> {
  const openStore = params.openStore ?? openHermesSessionStore;
  const deadline = Date.now() + params.timeoutMs;
  for (;;) {
    const id = tryDiscover(openStore, params.stateDbPath, params.sinceEpochSeconds);
    if (id) {
      return id;
    }
    if (Date.now() >= deadline) {
      return null;
    }
    await sleep(params.intervalMs);
  }
}
