import type { ScmCapabilities } from './scm';

export function createScmCapabilities(input?: Partial<ScmCapabilities>): ScmCapabilities {
  const changeSetModel = input?.changeSetModel ?? 'working-copy';
  const supportedDiffAreas =
    input?.supportedDiffAreas ??
    (changeSetModel === 'index' ? ['included', 'pending', 'both'] : ['pending', 'both']);

  return {
    readStatus: input?.readStatus ?? false,
    readDiffFile: input?.readDiffFile ?? false,
    readDiffCommit: input?.readDiffCommit ?? false,
    readLog: input?.readLog ?? false,
    readBranches: input?.readBranches ?? false,
    readStash: input?.readStash ?? false,
    writeInclude: input?.writeInclude ?? false,
    writeExclude: input?.writeExclude ?? false,
    writeDiscard: input?.writeDiscard ?? false,
    writeCommit: input?.writeCommit ?? false,
    writeCommitPathSelection: input?.writeCommitPathSelection ?? false,
    writeCommitLineSelection: input?.writeCommitLineSelection ?? false,
    writeBackout: input?.writeBackout ?? false,
    writeBranchCreate: input?.writeBranchCreate ?? false,
    writeBranchCheckout: input?.writeBranchCheckout ?? false,
    writeBranchMerge: input?.writeBranchMerge ?? false,
    writeBranchRebase: input?.writeBranchRebase ?? false,
    writeBranchOperationControl: input?.writeBranchOperationControl ?? false,
    writeRemoteAdd: input?.writeRemoteAdd ?? false,
    writeRemoteSetUrl: input?.writeRemoteSetUrl ?? false,
    writeRemoteRemove: input?.writeRemoteRemove ?? false,
    writeRemoteFetch: input?.writeRemoteFetch ?? false,
    writeRemotePull: input?.writeRemotePull ?? false,
    writeRemotePush: input?.writeRemotePush ?? false,
    writeRemotePublish: input?.writeRemotePublish ?? false,
    writeRepositoryInit: input?.writeRepositoryInit ?? false,
    readHostingRepositoryPublishTargets: input?.readHostingRepositoryPublishTargets ?? false,
    writeHostingRepositoryPublish: input?.writeHostingRepositoryPublish ?? false,
    writeStash: input?.writeStash ?? false,
    readHostingProvider: input?.readHostingProvider ?? false,
    readPullRequests: input?.readPullRequests ?? false,
    writePullRequestCreate: input?.writePullRequestCreate ?? false,
    writePullRequestCheckout: input?.writePullRequestCheckout ?? false,
    writePullRequestPrepareWorktree: input?.writePullRequestPrepareWorktree ?? false,
    writePullRequestRunStacked: input?.writePullRequestRunStacked ?? false,
    defaultBranchPushPolicy: input?.defaultBranchPushPolicy ?? 'deny',
    worktreeCreate: input?.worktreeCreate ?? false,
    changeSetModel,
    supportedDiffAreas,
    ...(input?.operationLabels ? { operationLabels: input.operationLabels } : {}),
  };
}

export function createGitScmCapabilities(input?: Partial<ScmCapabilities>): ScmCapabilities {
  return createScmCapabilities({
    readStatus: true,
    readDiffFile: true,
    readDiffCommit: true,
    readLog: true,
    readBranches: true,
    readStash: true,
    writeInclude: true,
    writeExclude: true,
    writeDiscard: true,
    writeCommit: true,
    writeCommitPathSelection: true,
    writeCommitLineSelection: true,
    writeBackout: true,
    writeBranchCreate: true,
    writeBranchCheckout: true,
    writeBranchMerge: true,
    writeBranchRebase: true,
    writeBranchOperationControl: true,
    writeRemoteAdd: true,
    writeRemoteSetUrl: true,
    writeRemoteRemove: true,
    writeRemoteFetch: true,
    writeRemotePull: true,
    writeRemotePush: true,
    writeRemotePublish: true,
    writeRepositoryInit: true,
    readHostingRepositoryPublishTargets: true,
    writeHostingRepositoryPublish: true,
    writeStash: true,
    readHostingProvider: true,
    readPullRequests: true,
    writePullRequestCreate: true,
    writePullRequestCheckout: true,
    writePullRequestPrepareWorktree: true,
    writePullRequestRunStacked: true,
    defaultBranchPushPolicy: 'requires-feature-branch',
    worktreeCreate: true,
    changeSetModel: 'index',
    supportedDiffAreas: ['included', 'pending', 'both'],
    operationLabels: {
      commit: 'Commit staged',
    },
    ...input,
  });
}

export function createSaplingScmCapabilities(input?: Partial<ScmCapabilities>): ScmCapabilities {
  return createScmCapabilities({
    readStatus: true,
    readDiffFile: true,
    readDiffCommit: true,
    readLog: true,
    readBranches: false,
    readStash: false,
    writeInclude: false,
    writeExclude: false,
    writeDiscard: true,
    writeCommit: true,
    writeCommitPathSelection: true,
    writeCommitLineSelection: false,
    writeBackout: true,
    writeBranchCreate: false,
    writeBranchCheckout: false,
    writeBranchMerge: false,
    writeBranchRebase: false,
    writeBranchOperationControl: false,
    writeRemoteAdd: false,
    writeRemoteSetUrl: false,
    writeRemoteRemove: false,
    writeRemoteFetch: true,
    writeRemotePull: true,
    writeRemotePush: true,
    writeRemotePublish: false,
    writeStash: false,
    worktreeCreate: false,
    changeSetModel: 'working-copy',
    supportedDiffAreas: ['pending', 'both'],
    operationLabels: {
      commit: 'Commit changes',
    },
    ...input,
  });
}
