import { z } from 'zod';

export const SCM_OPERATION_ERROR_CODES = {
  NOT_REPOSITORY: 'NOT_REPOSITORY',
  INVALID_PATH: 'INVALID_PATH',
  INVALID_REQUEST: 'INVALID_REQUEST',
  COMMAND_FAILED: 'COMMAND_FAILED',
  CHANGE_APPLY_FAILED: 'CHANGE_APPLY_FAILED',
  COMMIT_REQUIRED: 'COMMIT_REQUIRED',
  CONFLICTING_WORKTREE: 'CONFLICTING_WORKTREE',
  REMOTE_AUTH_REQUIRED: 'REMOTE_AUTH_REQUIRED',
  REMOTE_UPSTREAM_REQUIRED: 'REMOTE_UPSTREAM_REQUIRED',
  REMOTE_NON_FAST_FORWARD: 'REMOTE_NON_FAST_FORWARD',
  REMOTE_FF_ONLY_REQUIRED: 'REMOTE_FF_ONLY_REQUIRED',
  REMOTE_REJECTED: 'REMOTE_REJECTED',
  REMOTE_NOT_FOUND: 'REMOTE_NOT_FOUND',
  REMOTE_ALREADY_EXISTS: 'REMOTE_ALREADY_EXISTS',
  BRANCH_OPERATION_IN_PROGRESS: 'BRANCH_OPERATION_IN_PROGRESS',
  BRANCH_OPERATION_NOT_IN_PROGRESS: 'BRANCH_OPERATION_NOT_IN_PROGRESS',
  FEATURE_UNSUPPORTED: 'FEATURE_UNSUPPORTED',
  BACKEND_UNAVAILABLE: 'BACKEND_UNAVAILABLE',
} as const;

export type ScmOperationErrorCode =
  (typeof SCM_OPERATION_ERROR_CODES)[keyof typeof SCM_OPERATION_ERROR_CODES];

export const ScmOperationErrorCodeSchema = z.enum([
  SCM_OPERATION_ERROR_CODES.NOT_REPOSITORY,
  SCM_OPERATION_ERROR_CODES.INVALID_PATH,
  SCM_OPERATION_ERROR_CODES.INVALID_REQUEST,
  SCM_OPERATION_ERROR_CODES.COMMAND_FAILED,
  SCM_OPERATION_ERROR_CODES.CHANGE_APPLY_FAILED,
  SCM_OPERATION_ERROR_CODES.COMMIT_REQUIRED,
  SCM_OPERATION_ERROR_CODES.CONFLICTING_WORKTREE,
  SCM_OPERATION_ERROR_CODES.REMOTE_AUTH_REQUIRED,
  SCM_OPERATION_ERROR_CODES.REMOTE_UPSTREAM_REQUIRED,
  SCM_OPERATION_ERROR_CODES.REMOTE_NON_FAST_FORWARD,
  SCM_OPERATION_ERROR_CODES.REMOTE_FF_ONLY_REQUIRED,
  SCM_OPERATION_ERROR_CODES.REMOTE_REJECTED,
  SCM_OPERATION_ERROR_CODES.REMOTE_NOT_FOUND,
  SCM_OPERATION_ERROR_CODES.REMOTE_ALREADY_EXISTS,
  SCM_OPERATION_ERROR_CODES.BRANCH_OPERATION_IN_PROGRESS,
  SCM_OPERATION_ERROR_CODES.BRANCH_OPERATION_NOT_IN_PROGRESS,
  SCM_OPERATION_ERROR_CODES.FEATURE_UNSUPPORTED,
  SCM_OPERATION_ERROR_CODES.BACKEND_UNAVAILABLE,
]);
