import { StyleSheet } from 'react-native-unistyles';

import { Typography } from '@/constants/Typography';

export const embeddedTerminalPaneStyles = StyleSheet.create((theme) => ({
    container: {
        flex: 1,
        minHeight: 0,
        minWidth: 0,
        backgroundColor: theme.colors.surface.base,
    },
    toolbar: {
        paddingHorizontal: 12,
        paddingTop: 10,
        paddingBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.inset,
        gap: 10,
    },
    toolbarLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        minWidth: 0,
        flex: 1,
    },
    toolbarTitle: {
        fontSize: 13,
        color: theme.colors.text.secondary,
        ...Typography.default('semiBold'),
    },
    toolbarRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    banner: {
        paddingHorizontal: 12,
        paddingTop: 8,
        paddingBottom: 8,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.base,
    },
    bannerUrl: {
        flex: 1,
        minWidth: 0,
        fontSize: 12,
        color: theme.colors.text.secondary,
        ...Typography.default(),
    },
    bannerActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        flexShrink: 0,
    },
    terminalSurface: {
        flex: 1,
        minHeight: 0,
        minWidth: 0,
        padding: 8,
    },
    quickKeysScroll: {
        marginTop: 8,
        flexGrow: 0,
    },
    quickKeysRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingRight: 8,
    },
    quickKey: {
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.inset,
    },
    quickKeyLabel: {
        fontSize: 12,
        color: theme.colors.text.secondary,
        ...Typography.default('semiBold'),
    },
    overlay: {
        ...StyleSheet.absoluteFillObject,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 16,
        backgroundColor: theme.colors.surface.base,
        opacity: 0.96,
    },
    overlayTitle: {
        fontSize: 14,
        color: theme.colors.text.secondary,
        textAlign: 'center',
        ...Typography.default('semiBold'),
    },
    overlayBody: {
        marginTop: 8,
        fontSize: 12,
        color: theme.colors.text.secondary,
        textAlign: 'center',
        ...Typography.default(),
    },
    overlayRetry: {
        marginTop: 14,
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.inset,
    },
    overlayRetryLabel: {
        fontSize: 12,
        color: theme.colors.text.primary,
        ...Typography.default('semiBold'),
    },
}));
