import { describe, expect, it, vi } from 'vitest';

import { createClaudeRawMessageTurnDiffBridge } from './createClaudeRawMessageTurnDiffBridge';

describe('createClaudeRawMessageTurnDiffBridge', () => {
  it('drops Claude local-command and system lifecycle records from visible transcript content', () => {
    const sendMessage = vi.fn();
    const bridge = createClaudeRawMessageTurnDiffBridge({
      getSessionId: () => 'happy-session-id',
      sendMessage,
    });

    const hiddenMessages = [
      {
        type: 'system',
        uuid: 'compact-boundary-1',
        subtype: 'compact_boundary',
      },
      {
        type: 'user',
        uuid: 'local-command-caveat-1',
        isMeta: true,
        message: {
          content: '<local-command-caveat>Generated by a local command.</local-command-caveat>',
        },
      },
      {
        type: 'user',
        uuid: 'compact-command-1',
        message: {
          content: '<command-name>/compact</command-name>\n<command-message>compact</command-message>',
        },
      },
      {
        type: 'user',
        uuid: 'compact-stdout-1',
        message: {
          content: [
            {
              type: 'text',
              text: [
                '<local-command-stdout>Compacted',
                'PreCompact [/Users/test/.claude/hooks/pre-compact.sh] completed successfully',
                'PostCompact [/Users/test/.claude/hooks/post-compact.sh] completed successfully</local-command-stdout>',
              ].join('\n'),
            },
          ],
        },
      },
    ];

    for (const message of hiddenMessages) {
      expect(bridge.observe(message as any)).toBeNull();
    }
    expect(sendMessage).not.toHaveBeenCalled();

    expect(bridge.observe({
      type: 'user',
      uuid: 'normal-user-1',
      message: { content: 'hello' },
    } as any)).toMatchObject({
      type: 'user',
      uuid: 'normal-user-1',
    });
  });
});
