import * as React from 'react';

import type { NewSessionSimplePanelProps } from '../components/NewSessionSimplePanel';

export function useNewSessionSimplePanelProps(
    params: NewSessionSimplePanelProps,
): NewSessionSimplePanelProps {
    return React.useMemo(() => ({
        popoverBoundaryRef: params.popoverBoundaryRef,
        headerHeight: params.headerHeight,
        safeAreaTop: params.safeAreaTop,
        safeAreaBottom: params.safeAreaBottom,
        newSessionTopPadding: params.newSessionTopPadding,
        newSessionSidePadding: params.newSessionSidePadding,
        newSessionBottomPadding: params.newSessionBottomPadding,
        containerStyle: params.containerStyle,
        sessionPrompt: params.sessionPrompt,
        setSessionPrompt: params.setSessionPrompt,
        handleCreateSession: params.handleCreateSession,
        canCreate: params.canCreate,
        isCreating: params.isCreating,
        emptyAutocompletePrefixes: params.emptyAutocompletePrefixes,
        emptyAutocompleteSuggestions: params.emptyAutocompleteSuggestions,
        sessionPromptInputMaxHeight: params.sessionPromptInputMaxHeight,
        automationSection: params.automationSection,
        submitAccessibilityLabel: params.submitAccessibilityLabel,
        agentInputExtraActionChips: params.agentInputExtraActionChips,
        agentType: params.agentType,
        agentLabel: params.agentLabel,
        handleAgentClick: params.handleAgentClick,
        agentPickerTitle: params.agentPickerTitle,
        agentPickerOptions: params.agentPickerOptions,
        agentPickerSelectedOptionId: params.agentPickerSelectedOptionId,
        onAgentPickerSelect: params.onAgentPickerSelect,
        agentPickerApplyLabel: params.agentPickerApplyLabel,
        permissionMode: params.permissionMode,
        handlePermissionModeChange: params.handlePermissionModeChange,
        modelMode: params.modelMode,
        setModelMode: params.setModelMode,
        modelOptions: params.modelOptions,
        modelOptionsProbe: params.modelOptionsProbe,
        acpSessionModeOptions: params.acpSessionModeOptions,
        acpSessionModeProbe: params.acpSessionModeProbe,
        acpSessionModeId: params.acpSessionModeId,
        setAcpSessionModeId: params.setAcpSessionModeId,
        acpConfigOptions: params.acpConfigOptions,
        acpConfigOptionsProbe: params.acpConfigOptionsProbe,
        acpConfigOptionOverrides: params.acpConfigOptionOverrides,
        setAcpConfigOptionOverride: params.setAcpConfigOptionOverride,
        connectionStatus: params.connectionStatus,
        machineName: params.machineName,
        handleMachineClick: params.handleMachineClick,
        selectedPath: params.selectedPath,
        handlePathClick: params.handlePathClick,
        showResumePicker: params.showResumePicker,
        resumeSessionId: params.resumeSessionId,
        handleResumeClick: params.handleResumeClick,
        isResumeSupportChecking: params.isResumeSupportChecking,
        useProfiles: params.useProfiles,
        selectedProfileId: params.selectedProfileId,
        handleProfileClick: params.handleProfileClick,
        profilePopover: params.profilePopover,
        selectedProfileEnvVarsCount: params.selectedProfileEnvVarsCount,
        envVarsPopover: params.envVarsPopover,
        targetServerId: params.targetServerId,
        attachmentFlowId: params.attachmentFlowId,
    }), [
        params.acpConfigOptionOverrides,
        params.acpConfigOptions,
        params.acpConfigOptionsProbe,
        params.acpSessionModeId,
        params.acpSessionModeOptions,
        params.acpSessionModeProbe,
        params.agentInputExtraActionChips,
        params.agentLabel,
        params.agentPickerApplyLabel,
        params.agentPickerOptions,
        params.agentPickerSelectedOptionId,
        params.agentPickerTitle,
        params.agentType,
        params.automationSection,
        params.canCreate,
        params.connectionStatus,
        params.containerStyle,
        params.emptyAutocompletePrefixes,
        params.emptyAutocompleteSuggestions,
        params.envVarsPopover,
        params.handleAgentClick,
        params.handleCreateSession,
        params.handleMachineClick,
        params.handlePathClick,
        params.handlePermissionModeChange,
        params.handleProfileClick,
        params.handleResumeClick,
        params.headerHeight,
        params.isCreating,
        params.isResumeSupportChecking,
        params.machineName,
        params.modelMode,
        params.modelOptions,
        params.modelOptionsProbe,
        params.newSessionBottomPadding,
        params.newSessionSidePadding,
        params.newSessionTopPadding,
        params.onAgentPickerSelect,
        params.permissionMode,
        params.popoverBoundaryRef,
        params.profilePopover,
        params.resumeSessionId,
        params.safeAreaBottom,
        params.safeAreaTop,
        params.selectedPath,
        params.selectedProfileEnvVarsCount,
        params.selectedProfileId,
        params.sessionPrompt,
        params.sessionPromptInputMaxHeight,
        params.setAcpConfigOptionOverride,
        params.setAcpSessionModeId,
        params.setModelMode,
        params.setSessionPrompt,
        params.showResumePicker,
        params.submitAccessibilityLabel,
        params.targetServerId,
        params.attachmentFlowId,
        params.useProfiles,
    ]);
}
