import type { AIBackendProfile } from '../../profiles/backendProfileSchema.js';
import { BUILT_IN_BACKEND_PROFILE_VERSION } from '../../profiles/builtInProfileVersion.js';

export const CODEX_BUILT_IN_BACKEND_PROFILES: ReadonlyArray<AIBackendProfile> = [
  {
    id: 'codex',
    name: 'Codex (Default)',
    authMode: 'machineLogin',
    requiresMachineLoginTargetKey: 'agent:codex',
    environmentVariables: [],
    defaultPermissionModeByTargetKey: { 'agent:codex': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': false, 'agent:codex': true, 'agent:gemini': false },
    compatibility: {},
    envVarRequirements: [],
    isBuiltIn: true,
    defaultEnabled: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_BACKEND_PROFILE_VERSION,
  },
  {
    id: 'openai',
    name: 'OpenAI (GPT-5)',
    envVarRequirements: [{ name: 'OPENAI_API_KEY', kind: 'secret', required: true }],
    environmentVariables: [
      { name: 'OPENAI_BASE_URL', value: 'https://api.openai.com/v1' },
      { name: 'OPENAI_MODEL', value: 'gpt-5-codex-high' },
      { name: 'OPENAI_API_TIMEOUT_MS', value: '600000' },
      { name: 'OPENAI_SMALL_FAST_MODEL', value: 'gpt-5-codex-low' },
      { name: 'API_TIMEOUT_MS', value: '600000' },
      { name: 'CODEX_SMALL_FAST_MODEL', value: 'gpt-5-codex-low' },
    ],
    defaultPermissionModeByTargetKey: { 'agent:codex': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': false, 'agent:codex': true, 'agent:gemini': false },
    compatibility: {},
    isBuiltIn: true,
    defaultEnabled: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_BACKEND_PROFILE_VERSION,
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI',
    envVarRequirements: [{ name: 'AZURE_OPENAI_API_KEY', kind: 'secret', required: true }],
    environmentVariables: [
      { name: 'AZURE_OPENAI_API_VERSION', value: '2024-02-15-preview' },
      { name: 'OPENAI_API_TIMEOUT_MS', value: '600000' },
      { name: 'API_TIMEOUT_MS', value: '600000' },
    ],
    defaultPermissionModeByTargetKey: { 'agent:codex': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': false, 'agent:codex': true, 'agent:gemini': false },
    compatibility: {},
    isBuiltIn: true,
    defaultEnabled: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_BACKEND_PROFILE_VERSION,
  },
] as const;
