export const PET_DRAG_THRESHOLD_PX = 4;
export const PET_VELOCITY_SAMPLE_WINDOW_MS = 100;
export const PET_VELOCITY_MIN_SPAN_MS = 16;
export const PET_VELOCITY_MIN_MAGNITUDE_PX_PER_S = 320;
export const PET_VELOCITY_MAX_MAGNITUDE_PX_PER_S = 1600;
