import type { AIBackendProfile } from '../../profiles/backendProfileSchema.js';
import { BUILT_IN_BACKEND_PROFILE_VERSION } from '../../profiles/builtInProfileVersion.js';

export const GEMINI_BUILT_IN_BACKEND_PROFILES: ReadonlyArray<AIBackendProfile> = [
  {
    id: 'gemini',
    name: 'Gemini (Default)',
    authMode: 'machineLogin',
    requiresMachineLoginTargetKey: 'agent:gemini',
    environmentVariables: [],
    defaultPermissionModeByTargetKey: { 'agent:gemini': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': false, 'agent:codex': false, 'agent:gemini': true },
    compatibility: {},
    envVarRequirements: [],
    isBuiltIn: true,
    defaultEnabled: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_BACKEND_PROFILE_VERSION,
  },
  {
    id: 'gemini-api-key',
    name: 'Gemini (API key)',
    envVarRequirements: [{ name: 'GEMINI_API_KEY', kind: 'secret', required: true }],
    environmentVariables: [],
    defaultPermissionModeByTargetKey: { 'agent:gemini': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': false, 'agent:codex': false, 'agent:gemini': true },
    compatibility: {},
    isBuiltIn: true,
    defaultEnabled: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_BACKEND_PROFILE_VERSION,
  },
  {
    id: 'gemini-vertex',
    name: 'Gemini (Vertex AI)',
    envVarRequirements: [
      { name: 'GOOGLE_CLOUD_PROJECT', kind: 'config', required: true },
      { name: 'GOOGLE_CLOUD_LOCATION', kind: 'config', required: true },
    ],
    environmentVariables: [
      { name: 'GOOGLE_GENAI_USE_VERTEXAI', value: '1' },
    ],
    defaultPermissionModeByTargetKey: { 'agent:gemini': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': false, 'agent:codex': false, 'agent:gemini': true },
    compatibility: {},
    isBuiltIn: true,
    defaultEnabled: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_BACKEND_PROFILE_VERSION,
  },
] as const;
